In [1]:
# Setup

In [2]:
EPOCHS = 150
BATCH_SIZE = 32
VAL_SPLIT = 0.33

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
# Manifest

In [4]:
job_types = [0, 1, 2]     # Full-time, Part-time, Contract
settings = [0, 1, 2]      # Remote, Hybrid, On-site
exp_levels = [0, 1, 2]    # Junior, Mid, Senior

mapping = {
    "job_types": ["full-time", "part-time", "contract"],
    "settings": ["remote", "hybrid", "on-site"],
    "exp_levels": ["junior", "mid", "senior"]
}

In [5]:
# Training

In [6]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

X_train = np.random.randint(0,3,size=(5000,6))

# 1. Extract the Job and User columns for comparison
job_types = X_train[:, 0]
job_settings = X_train[:, 1]
job_exps = X_train[:, 2]

user_types = X_train[:, 3]
user_settings = X_train[:, 4]
user_exps = X_train[:, 5]

# 2. Calculate matches (True/False arrays) multiplied by your weights
type_scores = (job_types == user_types).astype(int) * 50
setting_scores = (job_settings == user_settings).astype(int) * 30
exp_scores = (job_exps == user_exps).astype(int) * 20

# 3. Sum them up to get total scores for each of the 5000 rows
total_scores = type_scores + setting_scores + exp_scores

# 4. Apply the threshold to create the binary labels (0 or 1)
y_train = (total_scores >= 60).astype(int)

In [7]:
# The brain

In [8]:
from tensorflow.keras.callbacks import EarlyStopping

model = tf.keras.Sequential([
    layers.Dense(12, activation='relu', input_shape=(6,)), # Hidden Layer
    layers.Dense(1, activation='sigmoid')                 # Output Layer
])

# Add the Hidden Layer (12 neurons, 6 inputs, ReLU). 2 neurons per input is standard.
model.add(Dense(12, input_shape=(6,), activation='relu'))

# Add the Output Layer (1 neuron, Sigmoid). We simply need "0" for disliked, "1" for liked. 1 neuron for output is enough.
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

model.save("mlp_model.keras")

early_stopping = EarlyStopping(monitor='val_loss', patience=3)

model.fit(X_train, y_train, epochs=EPOCHS, batch_size=BATCH_SIZE, validation_split=VAL_SPLIT, callbacks=[early_stopping])

2026-02-20 10:23:05.575132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 47187 MB memory:  -> device: 0, name: Quadro RTX 8000, pci bus id: 0000:83:00.0, compute capability: 7.5
2026-02-20 10:23:05.575782: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 11542 MB memory:  -> device: 1, name: NVIDIA TITAN X (Pascal), pci bus id: 0000:02:00.0, compute capability: 6.1
2026-02-20 10:23:05.576332: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 11542 MB memory:  -> device: 2, name: NVIDIA TITAN X (Pascal), pci bus id: 0000:03:00.0, compute capability: 6.1


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 12)                84        
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
 dense_2 (Dense)             (None, 12)                24        
                                                                 
 dense_3 (Dense)             (None, 1)                 13        
                                                                 
Total params: 134 (536.00 Byte)
Trainable params: 134 (536.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/150


2026-02-20 10:23:07.324604: I external/local_xla/xla/service/service.cc:168] XLA service 0x7fc748cc34e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2026-02-20 10:23:07.324646: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (0): Quadro RTX 8000, Compute Capability 7.5
2026-02-20 10:23:07.324670: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (1): NVIDIA TITAN X (Pascal), Compute Capability 6.1
2026-02-20 10:23:07.324694: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (2): NVIDIA TITAN X (Pascal), Compute Capability 6.1
2026-02-20 10:23:07.331318: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2026-02-20 10:23:07.353730: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8800
I0000 00:00:1771579387.444835 2573805 device_compile

105/105 [==============================] - 3s 9ms/step - loss: 0.5311 - accuracy: 0.8191 - val_loss: 0.5002 - val_accuracy: 0.8074
Epoch 2/150
105/105 [==============================] - 1s 7ms/step - loss: 0.4764 - accuracy: 0.8191 - val_loss: 0.4873 - val_accuracy: 0.8074
Epoch 3/150
105/105 [==============================] - 1s 6ms/step - loss: 0.4703 - accuracy: 0.8191 - val_loss: 0.4874 - val_accuracy: 0.8074
Epoch 4/150
105/105 [==============================] - 1s 6ms/step - loss: 0.4693 - accuracy: 0.8191 - val_loss: 0.4863 - val_accuracy: 0.8074
Epoch 5/150
105/105 [==============================] - 1s 5ms/step - loss: 0.4683 - accuracy: 0.8191 - val_loss: 0.4853 - val_accuracy: 0.8074
Epoch 6/150
105/105 [==============================] - 1s 5ms/step - loss: 0.4671 - accuracy: 0.8191 - val_loss: 0.4841 - val_accuracy: 0.8074
Epoch 7/150
105/105 [==============================] - 1s 6ms/step - loss: 0.4654 - accuracy: 0.8191 - val_loss: 0.4826 - val_accuracy: 0.8074
Epoch 8/150

In [9]:
model.predict([[2,2,2,0,0,0]])

1/1 [==============================] - 0s 154ms/step


array([[0.12535349]], dtype=float32)

In [10]:
model.predict([[0,0,0,0,1,2]])

1/1 [==============================] - 0s 53ms/step


array([[0.16407287]], dtype=float32)

In [11]:
model.predict([[0,0,0,0,1,1]])

1/1 [==============================] - 0s 52ms/step


array([[0.2563776]], dtype=float32)

In [12]:
model.predict([[0,1,0,0,2,0]])

1/1 [==============================] - 0s 52ms/step


array([[0.8449227]], dtype=float32)

In [13]:
model.predict([[0,1,2,0,2,2]])

1/1 [==============================] - 0s 52ms/step


array([[0.83492064]], dtype=float32)

In [14]:
model.predict([[0,0,0,0,0,0]])

1/1 [==============================] - 0s 45ms/step


array([[0.8449227]], dtype=float32)